name: warzone2100
version: stable
version-script: cat $SNAPCRAFT_STAGE/version 
summary: A free and open source real time strategy game
icon: icons/warzone2100.large.png
description: |
  In Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.

  The game offers campaign, multi-player, and single-player skirmish modes. An extensive tech tree with over 400 different technologies, combined with the unit design system, allows for a wide variety of possible units and tactics.

  Warzone 2100 was originally developed as a commercial game by Pumpkin Studios and published in 1999, and was released as open source by them in 2004, for the community to continue working on it.

confinement: strict

apps:
  warzone2100:
    command: desktop-launch $SNAP/usr/bin/warzone2100
    plugs:
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - x11

  download-videos:
    command: download-videos
    plugs: [network]

parts:
  scripts:
    plugin: dump
    source: scripts
    override-build: |
      chmod +x download-videos
      snapcraftctl build
    organize:
      download-videos: bin/download-videos
    stage-packages:
      - curl

  sdl:
    source: https://www.libsdl.org/release/SDL2-2.0.8.tar.gz
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --disable-alsa
    - --disable-arts
    - --disable-esd
    - --disable-nas
    - --disable-oss
    build-packages:
    - fcitx-libs-dev
    - libegl1-mesa-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libibus-1.0-dev
    - libjack-dev
    - libpulse-dev
    - libsamplerate0-dev
    - libsndfile1-dev
    # - libts-dev # not available in xenial - touch screen library
    - libvulkan-dev
    - libwayland-dev
    - libx11-dev
    - libxcursor-dev
    - libxext-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - libxrender-dev
    - libxss-dev
    - libxxf86vm-dev
    stage-packages:
    - fcitx-libs
    - libdrm2
    - libegl1-mesa
    - libgl1
    - libgles2
    - libibus-1.0-5
    - libjack0
    - libpulse0
    - libsamplerate0
    # - libts0 # not available in xenial - touch screen library
    - libsndfile1
    - libwayland-client0
    - libwayland-egl1-mesa
    - libvulkan1
    - libx11-6
    - libxcursor1
    - libxext6
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1
    - libxss1
    - libxxf86vm1

  warzone2100:
    after: [desktop-qt5, sdl]
    source: https://github.com/Warzone2100/warzone2100.git
    override-build: |
      last_committed_tag="$(git  tag | grep -v beta | grep -v master | grep -v v | grep ^[1-9] | tail -n 1)"
      echo "last_committed_tag: $last_committed_tag"
      last_released_tag="$(snap info warzone2100 | awk '$1 == "beta:" { print $2 }')"
      echo "last_released_tag: $last_released_tag"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        echo "git fetch ..."
        git fetch
        echo "git checkout $last_committed_tag ..."
        git checkout "${last_committed_tag}"
      fi
      echo $last_committed_tag > $SNAPCRAFT_STAGE/version
      snapcraftctl build
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --disable-debug
    build-packages:
      - gettext
      - libcrypto++-dev
      - libcryptsetup-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libglc-dev
      - libglew-dev
      - libharfbuzz-dev
      - libopenal-dev
      - libphysfs-dev
      - libpng-dev
      - libqt5opengl5-dev
      - libssl-dev
      - libtheora-dev
      - libvorbis-dev
      - qtbase5-dev
      - qtscript5-dev
      - unzip
      - zip
    stage-packages:
      - libcrypto++9v5
      - libcryptsetup4
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libglc0
      - libglew1.13
      - libharfbuzz0b
      - libogg0
      - libopenal1
      - libphysfs1
      - libpng12-0
      - libqt5opengl5
      - libqt5script5
      - libssl1.0.0
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - unzip
      - zip
