name: warzone2100
version: stable
version-script: git -C parts/warzone2100/build describe --dirty 
summary: A free and open source real time strategy game
icon: icons/warzone2100.large.png
description: |
  In Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.

  The game offers campaign, multi-player, and single-player skirmish modes. An extensive tech tree with over 400 different technologies, combined with the unit design system, allows for a wide variety of possible units and tactics.

  Warzone 2100 was originally developed as a commercial game by Pumpkin Studios and published in 1999, and was released as open source by them in 2004, for the community to continue working on it.

confinement: strict

apps:
  warzone2100:
    command: desktop-launch $SNAP/usr/bin/warzone2100
    plugs:
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - x11

  download-videos:
    command: download-videos
    plugs: [network]

parts:
  scripts:
    plugin: dump
    source: scripts
    override-build: |
      chmod +x download-videos
      snapcraftctl build
    organize:
      download-videos: bin/download-videos
    stage-packages:
      - curl

  warzone2100:
    after: [desktop-qt5]
    source: https://github.com/Warzone2100/warzone2100.git
    override-build: |
      last_committed_tag="$(git tag | grep -v beta | grep -v master | grep -v v|  sort -n)"
      last_released_tag="$(snap info warzone2100 | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl build
    source-type: git
    source-depth: 1
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --disable-debug
    build-packages:
      - gettext
      - libcrypto++-dev
      - libcryptsetup-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libglc-dev
      - libglew-dev
      - libharfbuzz-dev
      - libopenal-dev
      - libphysfs-dev
      - libpng-dev
      - libqt5opengl5-dev
      - libsdl2-dev
      - libssl-dev
      - libtheora-dev
      - libvorbis-dev
      - qtbase5-dev
      - qtscript5-dev
      - unzip
      - zip
    stage-packages:
      - libcrypto++9v5
      - libcryptsetup4
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libglc0
      - libglew1.13
      - libharfbuzz0b
      - libopenal1
      - libphysfs1
      - libpng12-0
      - libqt5opengl5
      - libqt5script5
      - libsdl2-2.0-0
      - libssl1.0.0
      - libtheora0
      - libvorbis0a
      - unzip
      - zip
